config/routes.rb
ErrorNot::Application.routes.draw do
  resources :projects do

    member do
      put :add_member
      delete :remove_member
      get :leave
      delete :leave
      put :admins
      delete :admin
      put :reset_apikey
    end # member
    
    resources :errors, :except => [:new, :create, :update] do

      member do
        post :comment
        get :backtrace
        get :session_info
        get :data
        get :similar_error
        get :request_info
      end # member
      
      resources :same_errors, :only => [:show] do

        member do
          get :backtrace
          get :session_info
          get :data
          get :similar_error
          get :request_info
        end # member

      end # resources :same_errors

    end # resources :errors

  end # resources :projects

  resources :errors, :only => [:create, :update]

  devise_for :users
  
  resource :user do
    put :update_notify, :on => :collection
  end # resource :user
  
  root :to => "projects#index"
end # ErrorNot::Application.routes.draw

app/models/user.rb
class User

  include MongoMapper::Document

  ## Include default devise modules.
  ## Others available are :lockable, :timeoutable and :activatable.
  plugin MongoMapper::Devise
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable
  after_save :check_member_project
  validate :not_change_email


  def member_projects
    Project.all('members.user_id' => self.id)
  end

  ##
  # Change all notification of this user to all project
  # where he is member
  #
  # You can has notify :
  #  - :email => one email by error
  #  - :digest => one digest by time
  #  - :removal => one email when he is deleted
  #
  # @params[Hash] key are type of nofication, and value is a Array of
  # all project_id where notification is OK
  #
  def update_notify(notify={})
    member_projects.each do |project|
      member = project.member(self)
      member.notify_by_email =  (notify[:email]||[]).include?(project.id.to_s)
      member.notify_removal_by_email = (notify[:removal] || []).include?(project.id.to_s)
      member.notify_by_digest = (notify[:digest] || []).include?(project.id.to_s)
      member.save
    end
  end

  ##
  # Search all project where user is member by his email.
  #
  # In each project, update user_id if member is not validate
  # or has no user_id
  #
  def check_member_project
    Project.all('members.email' => self.email).each do |project|
      member = project.members.detect{ |member| member.email == self.email }
      if member.user_id.blank? || member.status != Member::VALIDATE
        # We need save member if member not validate
        # it's member who check if user is or not validate
        member.user_id = self.id
        member.save
      end
    end
  end

  def not_change_email
    if email_changed? && !email_was.blank?
      errors.add(:email, 'user.validation.email.not_change')
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]

  def new
    @user = User.new
    @user.email = params[:email]
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = t('devise.confirmations.send_instructions')
      redirect_to(new_user_session_url)
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    # Could be splitted in two actions
    method = params[:user][:password] ? :update_with_password : :update_attributes
    if @user.send(method, params[:user])
      flash[:notice] = t('flash.users.update.success') #'Updated successfully'
      redirect_to root_path
    else
      render :edit
    end
  end

  def update_notify
    current_user.update_notify(:email => params[:notify_by_email],
                               :removal => params[:notify_removal_by_email],
                               :digest => params[:notify_by_digest])
    flash[:notify_me] = t('flash.users.update.success_update_notify')
    redirect_to(edit_user_path)
  end

  def destroy
    current_user.destroy
    sign_out current_user
    flash[:notice] = t('flash.users.destroy.notice', :default => 'User was successfully destroyed.')
    redirect_to root_path
  end
end

app/views/users/edit.html.haml
- @title = t('views.users.edit.title')

%h1 Your Profile
%dl
  %dt Email:
  %dd= current_user.email

= form_for @user, :url => user_url do |f|
  = field_set_tag 'Update my password' do
    %p
      = f.label :current_password, 'Current password'
      = f.password_field :current_password
    %p.error
      = error_message_on @user, :current_password
    %p
      = f.label :password, 'New password'
      = f.password_field :password
    %p.error
      = error_message_on @user, :password
    %p
      = f.label :password_confirmation, 'Confirm the new password'
      = f.password_field :password_confirmation
    %p{:class => 'submit'}
      = f.submit 'Update my password'

= form_for @user, :url => update_notify_user_url do |f|
  = field_set_tag 'Notify me' do
    %table.small
      %thead
        %tr
          %th Project
          %th Notify new errors by email?
          %th Notify project removal by email?
          %th Notify new errors by digest?
      %tbody
        - @user.member_projects.each do |project|
          %tr
            %td= project.name
            %td= check_box_tag 'notify_by_email[]', project.id.to_s, project.member(@user).notify_by_email
            %td= check_box_tag 'notify_removal_by_email[]', project.id.to_s, project.member(@user).notify_removal_by_email
            %td
              = check_box_tag 'notify_by_digest[]', project.id.to_s, project.member(@user).notify_by_digest
              - if project.member(@user).digest_send_at
                Last digest sent on:
                = l project.member(@user).digest_send_at

    %p{:class => 'submit'}
      = f.submit 'Update notifications'

= link_to 'Close my account', user_path, :method => :delete, :confirm => 'Are you sure you want to close your account?'

app/views/users/new.html.haml
- @title = t('views.users.new.title')

= form_for @user, :url => user_path do |f|
  = f.error_messages
  %p= f.label :email
  %p= f.text_field :email
  %p= f.label :password
  %p= f.password_field :password
  %p= f.label :password_confirmation
  %p= f.password_field :password_confirmation

  %p.submit= f.submit "Sign Up"