config/routes.rb
ErrorNot::Application.routes.draw do
  resources :projects do

    member do
      put :add_member
      delete :remove_member
      get :leave
      delete :leave
      put :admins
      delete :admin
      put :reset_apikey
    end # member
    
    resources :errors, :except => [:new, :create, :update] do

      member do
        post :comment
        get :backtrace
        get :session_info
        get :data
        get :similar_error
        get :request_info
      end # member
      
      resources :same_errors, :only => [:show] do

        member do
          get :backtrace
          get :session_info
          get :data
          get :similar_error
          get :request_info
        end # member

      end # resources :same_errors

    end # resources :errors

  end # resources :projects

  resources :errors, :only => [:create, :update]

  devise_for :users
  
  resource :user do
    put :update_notify, :on => :collection
  end # resource :user
  
  root :to => "projects#index"
end # ErrorNot::Application.routes.draw

app/models/project.rb
class Project
  include MongoMapper::Document

  key :api_key, String, :required => true, :index => true
  key :name, String, :required => true

  key :nb_errors_reported, Integer, :default => 0
  key :nb_errors_resolved, Integer, :default => 0
  key :nb_errors_unresolved, Integer, :default => 0

  many :error_reports, :class_name => 'Error' do
    def not_send_by_digest_since(date)
      all(:unresolved_at => {'$gt' => date.utc},
          :resolved => false,
          :order => 'last_raised_at')
    end
  end

  many :members

  validate :need_members
  validate :need_admin_members

  validates_associated :members

  ## CALLBACK
  before_validation :gen_api_key, :on => :create
  before_save :update_members_data

  def add_admin_member(user)
    members.build(:user => user, :admin => true)
  end

  def make_user_admin!(user)
    member_obj = member(user)
    return false unless member_obj.status == Member::VALIDATE
    member_obj.admin = true
    save
  end

  def unmake_user_admin!(user)
    member(user).admin = false
    save
  end

  def member_include?(user)
    members.any?{|member| member.user_id == user.id}
  end

  def admin_member?(user)
    members.any?{|member| member.user_id == user.id && member.admin? }
  end

  def remove_member!(data={:user => nil, :email => nil})
    if data.key? :email
      members.delete_if{ |member| member.email == data[:email] }
    elsif data.key? :user
      members.delete_if{ |member| member.user_id.to_s == data[:user].id.to_s }
    end
    save
  end

  def update_nb_errors
    self.nb_errors_reported = error_reports.count
    self.nb_errors_unresolved = error_reports.count(:resolved => false)
    self.nb_errors_resolved = error_reports.count(:resolved => true)
    self.save!
  end

  ##
  # Add member to this project by emails.
  #
  # If user already exist with this email. Add it.
  # instead send an email to create his account
  #
  # @params[String] list of emails separate by comma
  # @return true if works
  def add_member_by_email(emails)
    emails.split(',').each do |email|
      user = User.first(:email => email.strip)
      if user
        members.build(:user => user,
                      :admin => false)
      else
        members.build(:email => email.strip,
                      :admin => false)
        UserMailer.project_invitation(email.strip, self).deliver
      end
    end
    save!
  end

  def member(user)
    members.detect{|member| member.user_id == user.id }
  end

  ##
  # Check if an error with same message
  # and backtrace are already in this project. If there are
  # already an error with same data, create an ErrorEmbedded in
  # this error
  #
  # @params[String] the message
  # @params[Array] the backtrace
  # @return[Object] an Error or ErrorEmbedded
  #
  def error_with_message_and_backtrace(message, backtrace)
    error = error_reports.first(:message => message,
                        :backtrace => backtrace,
                        :project_id => self.id)
    unless error
      error_reports.build(:message => message,
                          :backtrace => backtrace)
    else
      error.same_errors.build
    end
  end

  ##
  # Search in _keyworks and if resolved or not
  #
  # @params[Array] the conditions with key :resolved, :search, :page, :per_page
  # @return[Array] the result paginate
  #
  def paginate_errors_with_search(params)
    error_search = {}
    if params.key?(:resolved)
      error_search[:resolved] = true  if params[:resolved] == 'y'
      error_search[:resolved] = false  if params[:resolved] == 'n'
    end
    error_search[:_keywords] = {'$in' => params[:search].split(' ').map(&:strip)} unless params[:search].blank?
    desc = params[:asc_order] || -1
    sorting = []
    if params.key?(:sort_by) && ['nb_comments', 'count'].include?(params[:sort_by])
      sorting << [params[:sort_by], desc]
      desc = -1 # the order by raised_at will then by descending
    end
    sorting << ['last_raised_at', desc.to_i]
    error_reports.paginate(:conditions => error_search,
             :page => params[:page] || 1,
             :per_page => params[:per_page] || 10,
             :sort => sorting)
  end

  # ClassMethod
  class << self
    def access_by(user)
      Project.all('members.user_id' => user.id)
    end

    def with_digest_request
      Project.all('members.notify_by_digest' => true)
    end
  end

  def gen_api_key!
    gen_api_key
    save
  end

  def gen_api_key
    self.api_key = SecureRandom.hex(12)
  end

  private

  def need_members
    errors.add(:members, 'need_member') if members.empty?
  end

  def need_admin_members
    errors.add(:members, 'need_admin_member') unless members.any?{ |m| m.admin }
  end

  def update_members_data
    members.each do |member|
      member.update_data
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_project, :only => [:edit, :update, :add_member, :remove_member,
                                         :leave, :destroy, :reset_apikey, :admins]
  before_filter :project_admin, :only => [:edit, :update, :add_member, :remove_member,
                                          :destroy, :reset_apikey, :admins]

  def index
    @projects = Project.access_by(current_user)
  end

  def new
    @project = Project.new
  end

  def show
    redirect_to project_errors_url(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    @project.add_admin_member(current_user)
    if @project.save
      flash[:notice] = "The project #{@project.name} has been successfully created"
      redirect_to(project_errors_url(@project))
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = t('flash.projects.update.success')
      redirect_to(project_errors_url(@project))
    else
      render :edit
    end
  end

  def add_member
    @project.add_member_by_email(params[:email])
    flash[:notice] = t('flash.projects.add_member.success')
    redirect_to edit_project_url(@project)
  end

  def remove_member
    email = params[:user_email]
    if !email.blank? && @project.remove_member!(:email => email)
      flash[:notice] = t('flash.projects.remove_member.success')
      UserMailer.project_removal(email, current_user.email, @project).deliver
    else
      flash[:notice] = t('flash.projects.remove_member.failure')
    end
    redirect_to edit_project_url(@project)
  end

  def leave
    if request.delete?
      # delete member of this project
      if !@project.admin_member?(current_user) &&
        @project.remove_member!(:user => current_user)
        flash[:notice] = t('flash.projects.leave.success',
                           :project_name => @project.name)
      else
        flash[:notice] = t('flash.projects.leave.refused')
      end
      redirect_to projects_url
      return
    end
  end

  def admins
    user = User.find(params[:user_id])
    if user.blank?
      flash[:notice] = t('flash.projects.admin.failure')
    elsif request.put? && @project.make_user_admin!(user)
      flash[:notice] = t('flash.projects.admin.add.success')
    elsif request.delete? && @project.unmake_user_admin!(user)
      flash[:notice] = t('flash.projects.admin.delete.success')
    else
      flash[:notice] = t('flash.projects.admin.failure')
    end
    redirect_to edit_project_url(@project)
  end

  def reset_apikey
    if request.put?
      @project.gen_api_key!
      redirect_to edit_project_url(@project)
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = t('flash.projects.destroy.notice', :default => 'Project was successfully destroyed.')
    redirect_to projects_url
  end

  private

  def load_project
    @project = Project.find!(params[:id])
  end

  def project_admin
    render_401 unless @project.admin_member?(current_user)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def member_status(member_status)
    case member_status
    when Member::AWAITING
      I18n.t('member.status.awaiting')
    when Member::UNVALIDATE
      I18n.t('member.status.unvalidate')
    when Member::VALIDATE
      I18n.t('member.status.validate')
    end
  end

  def change_power(member)
    confirm = nil
    if member.user.id == current_user.id
      confirm =  "You are are going to loose your admin rights! Confirm?"
    end
    if member.admin?
       link_to 'Admin', admins_project_url(@project, :user_id=>member.user.id), :method => :delete, 
         :confirm => confirm, :title => "Remove admin rights"
    else
      link_to 'Not Admin', admins_project_url(@project, :user_id=>member.user.id), :method => :put,
        :title => "Make admin"
    end
  end

  def trash_member(member)
    link_to 'Remove', remove_member_project_url(@project, :user_email=>member.email), :method => :delete, 
         :confirm => "Are you sure you want to remove #{member.email || 'user'} from the project?", 
         :title => "Remove the user from the project"
  end
end

app/views/projects/edit.html.haml
- @title = t('views.projects.edit.title')

%h1 Update your project

%p
  = "API key: #{@project.api_key}"
  = link_to 'Reset', reset_apikey_project_url(@project), :method => :put

= field_set_tag 'Project' do
  = error_messages_for :project

  = form_for @project do |f|
    %p
      %label='Name :'
      = f.text_field :name
    %p
      = f.submit 'update'

= field_set_tag 'Members' do
  = form_tag add_member_project_url(@project), :method => :put do
    %p
      = label_tag 'Email'
      %br/
      = text_field_tag :email
    %p{:class => 'submit'}
      = submit_tag 'Add member'

%h2 Members list

%table
  %thead
    %tr
      %th Email
      %th Status
      %th Admin
      %th Trash
  %tbody
    - @project.members.each do |member|
      %tr
        %td= member.email
        %td= member_status(member.status)
        %td= change_power(member)
        %td= trash_member(member)

app/views/projects/index.html.haml
- @title = t('views.projects.index.title')

%h1= t('views.projects.index.h1')

- unless @projects.empty?
  %table
    %thead
      %tr
        %th= t('views.projects.index.project_name')
        %th= t('views.projects.index.reported_errors')
        %th= t('views.projects.index.resolved_errors')
        %th= t('views.projects.index.pending_errors')
        %th= t('views.projects.index.stop_following')
    %tbody
      -@projects.each do |project|
        %tr
          %td= link_to project.name, project_errors_path(project)
          %td.center= link_to project.nb_errors_reported, project_errors_path(project)
          %td.center= link_to project.nb_errors_resolved, project_errors_path(project, :resolved => 'y')
          %td.center= link_to project.nb_errors_unresolved, project_errors_path(project, :resolved => 'n')
          - unless project.admin_member?(current_user)
            %td.center= link_to t('views.projects.index.leave_it'),leave_project_url(project)
          - else
            %td.center= t('views.projects.index.can_t_unfollow')
  %p
    =link_to t('views.projects.index.create_project'), new_project_path
- else
  %p
    = t('views.projects.index.no_project')
    = link_to t('views.projects.index.first_project'), new_project_path

app/views/projects/leave.html.haml
%h1 Leave project #{@project.name}

- if @project.admin_member?(current_user)
  %p You can't leave project because you are admin on it
- else
  %p
    you want really leave this project ?

  = form_tag leave_project_url(@project), :method => :delete do
    = submit_tag 'Leave'

app/views/projects/new.html.haml
- @title = t('views.projects.new.title')

%h1 Create a new project

= error_messages_for :project

= form_for @project do |f|
  %p
    %label='Name :'
    = f.text_field :name
  %p
    = f.submit 'Create'