config/routes.rb
ErrorNot::Application.routes.draw do
  resources :projects do

    member do
      put :add_member
      delete :remove_member
      get :leave
      delete :leave
      put :admins
      delete :admin
      put :reset_apikey
    end # member
    
    resources :errors, :except => [:new, :create, :update] do

      member do
        post :comment
        get :backtrace
        get :session_info
        get :data
        get :similar_error
        get :request_info
      end # member
      
      resources :same_errors, :only => [:show] do

        member do
          get :backtrace
          get :session_info
          get :data
          get :similar_error
          get :request_info
        end # member

      end # resources :same_errors

    end # resources :errors

  end # resources :projects

  resources :errors, :only => [:create, :update]

  devise_for :users
  
  resource :user do
    put :update_notify, :on => :collection
  end # resource :user
  
  root :to => "projects#index"
end # ErrorNot::Application.routes.draw

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ErrorNot</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html{ :lang => "en" }
  %head
    %meta{ :content => "text/html; charset=utf-8", "http-equiv" => "Content-Type" }
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    %title= title_header
  %body
    %header
      %p
        %a{ :href => "/" }
          %span.hide
            ErrorNot
      - if user_signed_in?
        %ul
          %li= link_to t('layout.user_nav.profile'), edit_user_url
          %li= link_to t('layout.user_nav.logout'), destroy_user_session_url, :method => :delete

    %nav
      - if user_signed_in?
        %ul
          %li= link_to t('layout.menu.projects'), projects_url


    #content
      = yield :summary
      = flash_to_html(flash)
      = yield

    %footer
      %p
        Powered by
        %a{ :href => "http://github.com/errornot/ErrorNot/" }
          %span
            Errornot
        \-
        = ::Errornot::VERSION